plugins {
    id 'java'
}

group = 'com.vit.demo'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.register('runTest', JavaExec) {
    group = 'verification'
    description = 'Runs the demonstration test.'
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.vit.demo.AppTest'
}

tasks.named('test') {
    dependsOn tasks.named('runTest')
    failOnNoDiscoveredTests = false
}

jar {
    archiveBaseName = 'ci-jenkins-demo'
    archiveVersion = '1.0.0'
    manifest {
        attributes 'Main-Class': 'com.vit.demo.App'
    }
}